In [3]:
# NumPy

In [4]:
%pip install numpy


[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
# Array is a powerful grid used to store a collection of data—usually numbers—where every item is of the same type.

In [ ]:
# An array is a data structure consisting of a collection of elements of the same data type, stored in 
# contiguous memory locations and identified by at least one array index or key

In [7]:
# Creating Arrays

In [8]:
# 1D Array (also known as a Vector).

In [9]:
sample_array = np.array([1, 2, 3, 4])
print(sample_array)

[1 2 3 4]


In [10]:
# 2D Array (a matrix) with 2 rows and 2 columns.

In [11]:
sample_array_2 = np.array([[1, 2], [3, 4]])
print(sample_array_2)

[[1 2]
 [3 4]]


In [ ]:
# 3D tensor is a collection of 2D matrices stacked together, 
# represented in NumPy as a nested array with three axes: depth, rows, and columns.

In [90]:
# 3D Tensor (2 matrices, each with 2 rows and 2 columns)

In [ ]:
sample_tensor_3 = np.array([
    [[1, 2], [3, 4]], # First matrix
    [[5, 6], [7, 8]]  # Second matrix
])

print(sample_tensor_3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# Array Properties

In [13]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [14]:
print(sample_array.shape) # (rows, columns)

(2, 3)


In [15]:
# Dimension (also called an axis) refers to the number of directions needed to find a specific piece of data.

# 0-D Array (Scalar): A single number (e.g., 5). It has no dimensions.
# 1-D Array (Vector): A simple list of numbers (e.g., [1, 2, 3]). You only need one index to find a value.
# 2-D Array (Matrix): A table with rows and columns. You need two indices (row, column) to find a value.
# 3-D Array (Tensor): A stack of tables (like a book of spreadsheets). You need three indices (page, row, column) to find a value. 


In [16]:
print(sample_array.ndim) # dimensions

2


In [17]:
print(sample_array.size) # total elements

6


In [18]:
print(sample_array.dtype) # data type

int64


In [19]:
# Special Arrays

In [20]:
np.zeros((2,3))   # all zer

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))    # all ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(0,10,2) # range

array([0, 2, 4, 6, 8])

In [23]:
# np.arange(start, stop, step)
# Focuses on the interval between numbers.
# Result: [0, 2, 4, 6, 8]
# Behavior: Similar to Python's range. It starts at 0 and adds 2 repeatedly. It excludes the stop value (10).
# Best Use: When you know exactly how far apart you want your numbers to be.

In [24]:
np.linspace(0,1,5) # equally spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# np.linspace(start, stop, num)
# Focuses on the total count of numbers.
# Result: [0. , 0.25, 0.5 , 0.75, 1. ]
# Behavior: "Linear Space." It squeezes exactly 5 numbers between 0 and 1. It includes the stop value (1) by default.
# Best Use: When you need a specific number of points to create a smooth line or graph.

In [26]:
# Indexing & Slicing

In [27]:
sample_array = np.array([10,20,30,40])

In [28]:
print(sample_array[0])      # first element

10


In [ ]:
print(sample_array[1:3])    # slicing
# The simplest way to remember slicing is: [Start : Stop before]

[20 30]


In [30]:
# 2D indexing

In [31]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [32]:
print(sample_array[0,1])   # row 0, col 1

2


In [33]:
# Array Operations

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [35]:
print(a + b)

[5 7 9]


In [36]:
print(a - b)

[-3 -3 -3]


In [37]:
print(a * b)

[ 4 10 18]


In [38]:
print(a / b)

[0.25 0.4  0.5 ]


In [39]:
# Mathematical Functions

In [40]:
sample_array = np.array([1,4,9])

In [41]:
print(np.sqrt(sample_array))

[1. 2. 3.]


In [42]:
# In NumPy, exponential refers to raising the constant e𝑒
# (Euler's number, approximately 2.718) to the power of each element in your array.

In [43]:
print(np.exp(sample_array))

[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [44]:
print(np.log(sample_array))

[0.         1.38629436 2.19722458]


In [45]:
# Statistical Functions

In [46]:
sample_array = np.array([1,2,3,4,5])

In [47]:
print(np.mean(sample_array))

3.0


In [48]:
print(np.median(sample_array))

3.0


In [49]:
print(np.std(sample_array))

1.4142135623730951


In [50]:
print(np.sum(sample_array))

15


In [51]:
print(np.min(sample_array))

1


In [52]:
print(np.max(sample_array))

5


In [53]:
# Reshaping Arrays

In [ ]:
# np.arange() generates an array of evenly spaced values within 
# a given interval, defined by a start (inclusive), stop (exclusive), and an optional step size.

In [54]:
sample_array = np.arange(6)

In [55]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [56]:
reshaped = sample_array.reshape(2,3)

In [57]:
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [58]:
# Flattening

In [59]:
sample_array = np.array([[1,2],[3,4]])

In [60]:
sample_array

array([[1, 2],
       [3, 4]])

In [61]:
print(sample_array.flatten())

[1 2 3 4]


In [62]:
# Joining Arrays

In [63]:
a = np.array([1,2])

In [64]:
b = np.array([3,4])

In [65]:
print(np.concatenate((a,b)))

[1 2 3 4]


In [66]:
# Splitting Arrays

In [67]:
sample_array = np.array([1,2,3,4])

In [68]:
print(np.array_split(sample_array, 2))

[array([1, 2]), array([3, 4])]


In [69]:
# Sorting

In [70]:
sample_array = np.array([3,1,2])

In [71]:
print(np.sort(sample_array))

[1 2 3]


In [72]:
# Searching

In [73]:
sample_array = np.array([1,2,3,4])

In [74]:
print(np.where(sample_array == 3))

(array([2]),)


In [75]:
# Random Module

In [76]:
np.random.rand(3)       # random floats

array([0.27663641, 0.41250919, 0.30312299])

In [77]:
np.random.randint(1,10,5) # random integers

array([4, 2, 2, 6, 9])

In [78]:
# Axis Concept

In [79]:
# In NumPy, Axis is just another word for Dimension. 
# You use axes to tell NumPy which direction to perform a calculation (like summing numbers).

In [80]:
sample_array = np.array([[1,2],[3,4]])

In [81]:
print(np.sum(sample_array, axis=0))  # column-wise

[4 6]


In [82]:
print(np.sum(sample_array, axis=1))  # row-wise

[3 7]


In [83]:
# NaN & Missing Values

In [84]:
# In NumPy, NaN stands for "Not a Number". 
# It is a special floating-point value used to represent missing or undefined data.

In [85]:
sample_array = np.array([1, np.nan, 3])

In [86]:
print(np.isnan(sample_array))

[False  True False]


In [87]:
print(np.nanmean(sample_array))

2.0
